spring.application.name=FinAna

spring.config.import=optional:classpath:secrets-dev.properties

logging.level.root=INFO

spring.threads.virtual.enabled=true

spring.codec.max-in-memory-size=20MB

# Spring Boot 3.2+ only ? affects only WebClient
spring.webflux.client.max-in-memory-size=20MB

spring.mongodb.auto-index-creation=true

deepresearch.base-url=http://localhost:8081
